version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: beer_db
      POSTGRES_USER: beer_user
      POSTGRES_PASSWORD: beer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/beer_db
      SPRING_DATASOURCE_USERNAME: beer_user
      SPRING_DATASOURCE_PASSWORD: beer_password

volumes:
  postgres_data:
