spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/beer_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create
        show-sql: true
  logging:
    level:
      org:
        springframework:
          INFO
    pattern:
      console:
        d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n




